### ISSUE TITLE
Scarecrow stopped working on our Discord server.

### ISSUE THREAD

**Issue by jeff424242** [PapyrusThePlant/Scarecrow#3]
We have Scarecrow running on our Discord server, though there's no Twitter feeds coming from any of the feeds Scarecrow was following.  When we try to have Scarecrow follow another Twitter feed, it reports the following:

Scarecrow: follow command is disabled

This lack of Twitter feeds has been going on since Tuesday as a time reference.

**Comment by PapyrusThePlant** [comment]
Join the [support server](https://discord.gg/M85dw9u) for news and announcements about this and more.
