### ISSUE TITLE
Trying to add/search a Twitter profile

### ISSUE THREAD

**Issue by Cjnator38** [PapyrusThePlant/Scarecrow#6]
![image](https://user-images.githubusercontent.com/39870226/49120117-0e4db500-f271-11e8-877d-fa26b302219a.png)

**Comment by Cjnator38** [comment]
(Just realized I did the wrong prefix)
But I had this issue before

**Comment by PapyrusThePlant** [comment]
`search` is not a command, you want to use `twitter search`.
You can use the `help` command if you're not sure of the syntax of a command.
