### ISSUE TITLE
Bot Offline

### ISSUE THREAD

**Issue by giacintoderenzo** [PapyrusThePlant/Scarecrow#8]
Did you take the bot offline? It shows up as offline, and hasn't worked in almost a month. Will you put bot back up, or will I have to host locally now? Thanks.

**Comment by PapyrusThePlant** [comment]
The bot is now back up.
Please join the [support server](https://discord.gg/M85dw9u) for general questions like those.

**Comment by giacintoderenzo** [comment]
Sorry, but the support server link you provided is invalid. The bot does appear to be back online, but it does not respond to any commands. I double checked permissions, as I have used the bot in the past, and everything is good on my end. To be specific, it was the twitter commands that do not work.
